// <auto-generated />
using System;
using CarMaintenance.Models.Car;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarMaintenance.Migrations.Car
{
    [DbContext(typeof(CarContext))]
    [Migration("20200512180915_added-insurance-and-revision-km")]
    partial class addedinsuranceandrevisionkm
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarMaintenance.Models.Car.CarDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActualKilometers");

                    b.Property<string>("Details");

                    b.Property<DateTime>("LastInsurance");

                    b.Property<DateTime>("LastPti");

                    b.Property<DateTime>("LastRevisionDate");

                    b.Property<int>("LastRevisionKm");

                    b.Property<DateTime>("LastVig");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int?>("PeriodicityId");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("PeriodicityId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarMaintenance.Models.Periodicity.CarPeriodicity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InsuranceMonths");

                    b.Property<int?>("PtiMonths");

                    b.Property<int?>("RevisionKm");

                    b.Property<int?>("RevisionMonths");

                    b.Property<int?>("VigMonths");

                    b.HasKey("Id");

                    b.ToTable("CarPeriodicity");
                });

            modelBuilder.Entity("CarMaintenance.Models.Car.CarDetails", b =>
                {
                    b.HasOne("CarMaintenance.Models.Periodicity.CarPeriodicity", "Periodicity")
                        .WithMany()
                        .HasForeignKey("PeriodicityId");
                });
#pragma warning restore 612, 618
        }
    }
}
